apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-operator.secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-operator.fullname" . }}
    app.kubernetes.io/part-of: ukc
data:
  ukcToken: {{ required "UKC token is required." .Values.ukc.token | b64enc | quote }}
