apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-operator.fullname" . }}
    app.kubernetes.io/part-of: ukc
