image:
  name: ghcr.io/unikraft-cloud/k8s-operator

#resources:
#  requests:
#    cpu:
#    memory:
#  limits:
#    cpu:
#    memory:

ukc:
  metro:
  token:

leaderElection:
  enabled: false

metricsSecure: true
