name: std

on:
  push:
    branches: [prod-staging]
  pull_request:
    branches: [prod-staging]
    paths:
      - '**'
      - '!.github/**'
      - .github/workflows/std.yaml
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write

jobs:
  check-static:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
    steps:
      - uses: actions/checkout@v5

      - name: Run go-check
        uses: unikraft-cloud/internal-actions/actions/go-check@prod-staging
        with:
          gh_pat: ${{ secrets.GH_PAT }}

  test:
    runs-on: ubuntu-latest
    needs:
      - check-static
    permissions:
      contents: read
      issues: read
      checks: write
    steps:
      - uses: actions/checkout@v5

      - name: Run go-test
        uses: unikraft-cloud/internal-actions/actions/go-test@prod-staging
        with:
          gh_pat: ${{ secrets.GH_PAT }}
